# Generated by Django 4.2.7 on 2023-11-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='deptname',
            new_name='name',
        ),
    ]
