# Generated by Django 4.2.7 on 2023-11-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
