# Generated by Django 4.2.7 on 2023-11-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_alter_order_gender_alter_order_phonenumber'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
