# Generated by Django 4.2.7 on 2023-11-03 07:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='material',
            field=multiselectfield.db.fields.MultiSelectField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='mailid',
            field=models.EmailField(max_length=100),
        ),
    ]
