# Generated by Django 4.2.7 on 2023-11-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_alter_materials_material_alter_order_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='material',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='order',
            name='materials',
        ),
        migrations.AddField(
            model_name='order',
            name='materials',
            field=models.ManyToManyField(to='storeapp.materials'),
        ),
    ]
