# Generated by Django 4.2.7 on 2023-11-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_rename_cname_course_name_and_more'),
        ('storeapp', '0006_alter_materials_material_remove_order_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deptname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
    ]
