# Generated by Django 4.2.7 on 2023-11-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_alter_order_cname_alter_order_deptname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cname',
            new_name='course',
        ),
    ]
